//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBM_SwarVandana.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DBM_SwarVandana.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter address..
        /// </summary>
        internal static string AddressRequired {
            get {
                return ResourceManager.GetString("AddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter amount paid..
        /// </summary>
        internal static string AmountPaid {
            get {
                return ResourceManager.GetString("AmountPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter attended by..
        /// </summary>
        internal static string AttendedByRequired {
            get {
                return ResourceManager.GetString("AttendedByRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Bank Name.
        /// </summary>
        internal static string BankNameRequire {
            get {
                return ResourceManager.GetString("BankNameRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter budget amount..
        /// </summary>
        internal static string BudgetAmountRequired {
            get {
                return ResourceManager.GetString("BudgetAmountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget already exists..
        /// </summary>
        internal static string BudgetExists {
            get {
                return ResourceManager.GetString("BudgetExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre already exists..
        /// </summary>
        internal static string CentreExists {
            get {
                return ResourceManager.GetString("CentreExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter centre ID..
        /// </summary>
        internal static string CentreIdRequired {
            get {
                return ResourceManager.GetString("CentreIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter centre name..
        /// </summary>
        internal static string CentreNameRequired {
            get {
                return ResourceManager.GetString("CentreNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Centre Open Date..
        /// </summary>
        internal static string CentreOpenDateRequired {
            get {
                return ResourceManager.GetString("CentreOpenDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter city ID..
        /// </summary>
        internal static string CityIdRequired {
            get {
                return ResourceManager.GetString("CityIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter city..
        /// </summary>
        internal static string CityRequired {
            get {
                return ResourceManager.GetString("CityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter confirm password..
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter contact number..
        /// </summary>
        internal static string ContactNumberRequired {
            get {
                return ResourceManager.GetString("ContactNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter course amount..
        /// </summary>
        internal static string CourseAmount {
            get {
                return ResourceManager.GetString("CourseAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter date of enquiry..
        /// </summary>
        internal static string DateOfEnquiryRequired {
            get {
                return ResourceManager.GetString("DateOfEnquiryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter date of expense..
        /// </summary>
        internal static string DateOfExpenseRequired {
            get {
                return ResourceManager.GetString("DateOfExpenseRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter date of payment.
        /// </summary>
        internal static string DateOfPaymentRequired {
            get {
                return ResourceManager.GetString("DateOfPaymentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter description..
        /// </summary>
        internal static string DescriptionRequired {
            get {
                return ResourceManager.GetString("DescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discipline already exists..
        /// </summary>
        internal static string DisciplineExists {
            get {
                return ResourceManager.GetString("DisciplineExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter discipline..
        /// </summary>
        internal static string DisciplineRequired {
            get {
                return ResourceManager.GetString("DisciplineRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Discipline..
        /// </summary>
        internal static string DisplaneSelect {
            get {
                return ResourceManager.GetString("DisplaneSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter date of birth..
        /// </summary>
        internal static string DOBRequired {
            get {
                return ResourceManager.GetString("DOBRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter doj..
        /// </summary>
        internal static string DOJRequired {
            get {
                return ResourceManager.GetString("DOJRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter email ID..
        /// </summary>
        internal static string EmailIdRequired {
            get {
                return ResourceManager.GetString("EmailIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter end date..
        /// </summary>
        internal static string EndDateRequired {
            get {
                return ResourceManager.GetString("EndDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter enquiry by..
        /// </summary>
        internal static string EnquiryByRequired {
            get {
                return ResourceManager.GetString("EnquiryByRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student enrollment already exists..
        /// </summary>
        internal static string Enrollexists {
            get {
                return ResourceManager.GetString("Enrollexists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter amount paid.
        /// </summary>
        internal static string EnterAmount {
            get {
                return ResourceManager.GetString("EnterAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter exam date..
        /// </summary>
        internal static string ExamDateRequired {
            get {
                return ResourceManager.GetString("ExamDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam detail already exists..
        /// </summary>
        internal static string ExamExists {
            get {
                return ResourceManager.GetString("ExamExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter exam fees..
        /// </summary>
        internal static string ExamFeesRequired {
            get {
                return ResourceManager.GetString("ExamFeesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter exam name..
        /// </summary>
        internal static string ExamRequired {
            get {
                return ResourceManager.GetString("ExamRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter expense amount..
        /// </summary>
        internal static string ExpenseAmountRequired {
            get {
                return ResourceManager.GetString("ExpenseAmountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense already exists..
        /// </summary>
        internal static string ExpenseExists {
            get {
                return ResourceManager.GetString("ExpenseExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter expense for..
        /// </summary>
        internal static string ExpenseForRequired {
            get {
                return ResourceManager.GetString("ExpenseForRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquiry already exists..
        /// </summary>
        internal static string ExquiryExists {
            get {
                return ResourceManager.GetString("ExquiryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty already exists..
        /// </summary>
        internal static string FacultyExists {
            get {
                return ResourceManager.GetString("FacultyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter faculty..
        /// </summary>
        internal static string FacultyIdRequired {
            get {
                return ResourceManager.GetString("FacultyIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter financial year..
        /// </summary>
        internal static string FinancialYearRequired {
            get {
                return ResourceManager.GetString("FinancialYearRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter first name..
        /// </summary>
        internal static string FNameRequired {
            get {
                return ResourceManager.GetString("FNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter gender..
        /// </summary>
        internal static string GenderRequired {
            get {
                return ResourceManager.GetString("GenderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetUsersForEnquiryBy.
        /// </summary>
        internal static string GetUsersForEnquiryBy {
            get {
                return ResourceManager.GetString("GetUsersForEnquiryBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Guardian Name.
        /// </summary>
        internal static string GuardianNameRequired {
            get {
                return ResourceManager.GetString("GuardianNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address..
        /// </summary>
        internal static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user name or password..
        /// </summary>
        internal static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid current password..
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter last name..
        /// </summary>
        internal static string LNameRequired {
            get {
                return ResourceManager.GetString("LNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter month..
        /// </summary>
        internal static string MonthRequired {
            get {
                return ResourceManager.GetString("MonthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter name..
        /// </summary>
        internal static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter new password..
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter no of classes..
        /// </summary>
        internal static string NoofClasses {
            get {
                return ResourceManager.GetString("NoofClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Occupation..
        /// </summary>
        internal static string Occupationrequired {
            get {
                return ResourceManager.GetString("Occupationrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is successfully changed..
        /// </summary>
        internal static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password not match..
        /// </summary>
        internal static string PasswordNotMatched {
            get {
                return ResourceManager.GetString("PasswordNotMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter password..
        /// </summary>
        internal static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter date..
        /// </summary>
        internal static string RemarksDateRequired {
            get {
                return ResourceManager.GetString("RemarksDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks already exists..
        /// </summary>
        internal static string RemarksExists {
            get {
                return ResourceManager.GetString("RemarksExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter remarks..
        /// </summary>
        internal static string RemarksRequired {
            get {
                return ResourceManager.GetString("RemarksRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter role ID..
        /// </summary>
        internal static string RoleIdRequired {
            get {
                return ResourceManager.GetString("RoleIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter salary..
        /// </summary>
        internal static string SalaryRequired {
            get {
                return ResourceManager.GetString("SalaryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source already exists..
        /// </summary>
        internal static string SourceExists {
            get {
                return ResourceManager.GetString("SourceExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter source name..
        /// </summary>
        internal static string SourceRequired {
            get {
                return ResourceManager.GetString("SourceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter start date..
        /// </summary>
        internal static string StartDateRequired {
            get {
                return ResourceManager.GetString("StartDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter state..
        /// </summary>
        internal static string StateRequired {
            get {
                return ResourceManager.GetString("StateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter status..
        /// </summary>
        internal static string StatusIdRequired {
            get {
                return ResourceManager.GetString("StatusIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student already exists..
        /// </summary>
        internal static string StudentExists {
            get {
                return ResourceManager.GetString("StudentExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter student..
        /// </summary>
        internal static string StudentRequired {
            get {
                return ResourceManager.GetString("StudentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget is successfully submitted..
        /// </summary>
        internal static string SubmitBudget {
            get {
                return ResourceManager.GetString("SubmitBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre is successfully submitted..
        /// </summary>
        internal static string SubmitCentre {
            get {
                return ResourceManager.GetString("SubmitCentre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class detail is successfully submitted..
        /// </summary>
        internal static string SubmitClass {
            get {
                return ResourceManager.GetString("SubmitClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discipline is successfully submitted..
        /// </summary>
        internal static string SubmitDisipline {
            get {
                return ResourceManager.GetString("SubmitDisipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquiry is successfully submitted..
        /// </summary>
        internal static string SubmitEnquiry {
            get {
                return ResourceManager.GetString("SubmitEnquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student enrollment is successfully submitted..
        /// </summary>
        internal static string SubmitEnroll {
            get {
                return ResourceManager.GetString("SubmitEnroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam detail is successfully submitted..
        /// </summary>
        internal static string SubmitExam {
            get {
                return ResourceManager.GetString("SubmitExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense is successfully submitted..
        /// </summary>
        internal static string SubmitExpense {
            get {
                return ResourceManager.GetString("SubmitExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty is successfully submitted..
        /// </summary>
        internal static string SubmitFaculty {
            get {
                return ResourceManager.GetString("SubmitFaculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment is successfully submitted..
        /// </summary>
        internal static string SubmitPayment {
            get {
                return ResourceManager.GetString("SubmitPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks is successfully submitted..
        /// </summary>
        internal static string SubmitRemarks {
            get {
                return ResourceManager.GetString("SubmitRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renewal is successfully submitted..
        /// </summary>
        internal static string SubmitRenewal {
            get {
                return ResourceManager.GetString("SubmitRenewal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source is successfully submitted..
        /// </summary>
        internal static string SubmitSource {
            get {
                return ResourceManager.GetString("SubmitSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student detail is successfully submitted..
        /// </summary>
        internal static string SubmitStudent {
            get {
                return ResourceManager.GetString("SubmitStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is successfully submitted..
        /// </summary>
        internal static string SubmitUsers {
            get {
                return ResourceManager.GetString("SubmitUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Cheque/Credit Card No.
        /// </summary>
        internal static string TransactionDetailsRequired {
            get {
                return ResourceManager.GetString("TransactionDetailsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists..
        /// </summary>
        internal static string UserExists {
            get {
                return ResourceManager.GetString("UserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter user name..
        /// </summary>
        internal static string UserNameRequired {
            get {
                return ResourceManager.GetString("UserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user name or password..
        /// </summary>
        internal static string UserNotExists {
            get {
                return ResourceManager.GetString("UserNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter year of experience..
        /// </summary>
        internal static string YearExpRequired {
            get {
                return ResourceManager.GetString("YearExpRequired", resourceCulture);
            }
        }
    }
}
