//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBM_SwarVandana.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Procedures {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Procedures() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DBM_SwarVandana.Resources.Procedures", typeof(Procedures).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllExpenses.
        /// </summary>
        internal static string GetAllExpenses {
            get {
                return ResourceManager.GetString("GetAllExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetBudgetForAll.
        /// </summary>
        internal static string GetBudgetForAll {
            get {
                return ResourceManager.GetString("GetBudgetForAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetClassByClassId.
        /// </summary>
        internal static string GetClassByClassId {
            get {
                return ResourceManager.GetString("GetClassByClassId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetClassByDisciplineId.
        /// </summary>
        internal static string GetClassByDisciplineId {
            get {
                return ResourceManager.GetString("GetClassByDisciplineId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetEnquiry.
        /// </summary>
        internal static string GetEnquiry {
            get {
                return ResourceManager.GetString("GetEnquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetEnquiryByEnquiryNumber.
        /// </summary>
        internal static string GetEnquiryByEnquiryNumber {
            get {
                return ResourceManager.GetString("GetEnquiryByEnquiryNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetEnquiryById.
        /// </summary>
        internal static string GetEnquiryById {
            get {
                return ResourceManager.GetString("GetEnquiryById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetExamDetailsByCentreID.
        /// </summary>
        internal static string GetExamDetailsByCentreID {
            get {
                return ResourceManager.GetString("GetExamDetailsByCentreID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetExamDetailsByExamID.
        /// </summary>
        internal static string GetExamDetailsByExamID {
            get {
                return ResourceManager.GetString("GetExamDetailsByExamID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetExpenseById.
        /// </summary>
        internal static string GetExpenseById {
            get {
                return ResourceManager.GetString("GetExpenseById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetExpensesForAll.
        /// </summary>
        internal static string GetExpensesForAll {
            get {
                return ResourceManager.GetString("GetExpensesForAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetStudentRemarksByCentreId.
        /// </summary>
        internal static string GetStudentRemarksByCentreId {
            get {
                return ResourceManager.GetString("GetStudentRemarksByCentreId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetStudentRemarksByRemarksID.
        /// </summary>
        internal static string GetStudentRemarksByRemarksID {
            get {
                return ResourceManager.GetString("GetStudentRemarksByRemarksID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetStudents.
        /// </summary>
        internal static string GetStudents {
            get {
                return ResourceManager.GetString("GetStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetStudentsByCentreId.
        /// </summary>
        internal static string GetStudentsByCentreId {
            get {
                return ResourceManager.GetString("GetStudentsByCentreId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetStudentsByUniqueId.
        /// </summary>
        internal static string GetStudentsByUniqueId {
            get {
                return ResourceManager.GetString("GetStudentsByUniqueId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetUsersForEnquiryBy.
        /// </summary>
        internal static string GetUsersForEnquiryBy {
            get {
                return ResourceManager.GetString("GetUsersForEnquiryBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InsertBudgetMaster.
        /// </summary>
        internal static string InsertBudgetMaster {
            get {
                return ResourceManager.GetString("InsertBudgetMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InsertExamDetails.
        /// </summary>
        internal static string InsertExamDetails {
            get {
                return ResourceManager.GetString("InsertExamDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InsertExpenses.
        /// </summary>
        internal static string InsertExpenses {
            get {
                return ResourceManager.GetString("InsertExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InsertStudentRemarks.
        /// </summary>
        internal static string InsertStudentRemarks {
            get {
                return ResourceManager.GetString("InsertStudentRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_Centres_IUD.
        /// </summary>
        internal static string USP_Centres_IUD {
            get {
                return ResourceManager.GetString("USP_Centres_IUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_CentresGetAll.
        /// </summary>
        internal static string USP_CentresGetAll {
            get {
                return ResourceManager.GetString("USP_CentresGetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_ChangePassword.
        /// </summary>
        internal static string USP_ChangePassword {
            get {
                return ResourceManager.GetString("USP_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_CitiesGetByStateId.
        /// </summary>
        internal static string USP_CitiesGetByStateId {
            get {
                return ResourceManager.GetString("USP_CitiesGetByStateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_ClassDetails_IUD.
        /// </summary>
        internal static string USP_ClassDetails_IUD {
            get {
                return ResourceManager.GetString("USP_ClassDetails_IUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_DisciplineGetAll.
        /// </summary>
        internal static string USP_DisciplineGetAll {
            get {
                return ResourceManager.GetString("USP_DisciplineGetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_DisciplineGetById.
        /// </summary>
        internal static string USP_DisciplineGetById {
            get {
                return ResourceManager.GetString("USP_DisciplineGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_Disciplines_IUD.
        /// </summary>
        internal static string USP_Disciplines_IUD {
            get {
                return ResourceManager.GetString("USP_Disciplines_IUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_Enquiries_IUD.
        /// </summary>
        internal static string USP_Enquiries_IUD {
            get {
                return ResourceManager.GetString("USP_Enquiries_IUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_Faculties_IUD.
        /// </summary>
        internal static string USP_Faculties_IUD {
            get {
                return ResourceManager.GetString("USP_Faculties_IUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_FacultyGetByCenterId.
        /// </summary>
        internal static string USP_FacultyGetByCenterId {
            get {
                return ResourceManager.GetString("USP_FacultyGetByCenterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_LoginCheck.
        /// </summary>
        internal static string USP_LoginCheck {
            get {
                return ResourceManager.GetString("USP_LoginCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_SourcesGetAll.
        /// </summary>
        internal static string USP_SourceGetAll {
            get {
                return ResourceManager.GetString("USP_SourceGetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_Sources_IUD.
        /// </summary>
        internal static string USP_Sources_IUD {
            get {
                return ResourceManager.GetString("USP_Sources_IUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_StatesGetAll.
        /// </summary>
        internal static string USP_StatesGetAll {
            get {
                return ResourceManager.GetString("USP_StatesGetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_StudentEntrollment_IUD.
        /// </summary>
        internal static string USP_StudentEntrollment_IUD {
            get {
                return ResourceManager.GetString("USP_StudentEntrollment_IUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_Students_IUD.
        /// </summary>
        internal static string USP_Students_IUD {
            get {
                return ResourceManager.GetString("USP_Students_IUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_Users_IUD.
        /// </summary>
        internal static string USP_Users_IUD {
            get {
                return ResourceManager.GetString("USP_Users_IUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_UsersGetAll.
        /// </summary>
        internal static string USP_UsersGetAll {
            get {
                return ResourceManager.GetString("USP_UsersGetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USP_UsersGetByUserId.
        /// </summary>
        internal static string USP_UsersGetByUserId {
            get {
                return ResourceManager.GetString("USP_UsersGetByUserId", resourceCulture);
            }
        }
    }
}
