//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBM_SwarVandana.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SmsMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SmsMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DBM_SwarVandana.Resources.SmsMessages", typeof(SmsMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for your visit to our Academy. Our batches r filling fast – come &amp; enrol.
        /// </summary>
        internal static string Enrolled {
            get {
                return ResourceManager.GetString("Enrolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request you to settle the outstanding amounts and Continue your classes..
        /// </summary>
        internal static string PaymentPending {
            get {
                return ResourceManager.GetString("PaymentPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for your visit to our Academy. Our batches r filling fast – come &amp; enrol.
        /// </summary>
        internal static string PETOENROLL {
            get {
                return ResourceManager.GetString("PETOENROLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your existing package needs to be renewed. Please renew in time and avail special offers..
        /// </summary>
        internal static string Renewal {
            get {
                return ResourceManager.GetString("Renewal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great to know of your interest in Music. Looking forward to your visit  for enrolment.
        /// </summary>
        internal static string TETOPE {
            get {
                return ResourceManager.GetString("TETOPE", resourceCulture);
            }
        }
    }
}
