//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBM_SwarVandana.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SmsMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SmsMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DBM_SwarVandana.Resources.SmsMessages", typeof(SmsMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are thankful for your support and co-operation. To make your experience even better, pl send your suggestions and inputs to sanjay@swarvanda.com.
        /// </summary>
        public static string CustomerFeedBack {
            get {
                return ResourceManager.GetString("CustomerFeedBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for enrolling with us. Welcome to the Svar Vandana family. Please start your classes as per the given schedule. Wishing you a  memorable Musical journey.
        /// </summary>
        public static string Enrolled {
            get {
                return ResourceManager.GetString("Enrolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As per our Records, there is a pending outstanding amount which kindly pay immediately and continue your classes as per the schedule given..
        /// </summary>
        public static string PaymentPending {
            get {
                return ResourceManager.GetString("PaymentPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for your visit to our Academy. We welcome u to enrol and begin your Musical Journey with us. Limited seats available - come &amp; enrol fast..
        /// </summary>
        public static string PETOENROLL {
            get {
                return ResourceManager.GetString("PETOENROLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hope you are having a wonderful experience with us. Your existing package is soon going to end. Pl Renew and Upgrade and avail special offers...
        /// </summary>
        public static string Renewal {
            get {
                return ResourceManager.GetString("Renewal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nice to  know of your interest in Music &amp; Dance. For a memorable musical experience pl visit  our Academy. Pl confirm a suitable date and time of your visit..
        /// </summary>
        public static string TETOPE {
            get {
                return ResourceManager.GetString("TETOPE", resourceCulture);
            }
        }
    }
}
